import Head from "next/head";
import { IUseditem } from "src/commons/types/graphql/types";
import { ItemCard } from "src/commons/ui/item-card";
import * as S from "./Home.styles";

interface IProps {
  itemsOfBestDatas?: IUseditem[] | null;
}

export default function HomeUI(props: IProps) {
  return (
    <>
      <Head>
        <title>상품 마켓</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <S.Wrapper>
        <S.CarouselWrapper autoplay>
          <div>
            <S.CarouselContent src="/images/banner-1.jpg" />
          </div>
          <div>
            <S.CarouselContent src="/images/banner-2.jpg" />
          </div>
          <div>
            <S.CarouselContent src="/images/banner-3.jpg" />
          </div>
        </S.CarouselWrapper>
        <S.BestItemsWrapper>
          <S.BestItemTitle>베스트 상품</S.BestItemTitle>
          <S.ItemsWrapper>
            {props.itemsOfBestDatas &&
              props.itemsOfBestDatas?.map((el) => (
                <ItemCard
                  key={el._id}
                  title={el.name}
                  remarks={el.remarks}
                  price={el.price ?? 0}
                  pickCount={el.pickedCount ?? 0}
                />
              ))}
          </S.ItemsWrapper>
        </S.BestItemsWrapper>
      </S.Wrapper>
    </>
  );
}
